name: Build/deploy website

env:
  ZOLA_VERSION: "0.13.0"
  SOURCE_BRANCH: "source"
  PUBLISH_BRANCH: "master"

on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: validate JSON
      run: |
        find . -type f -name '*.json' -print0 | xargs -0 -i python -c "import json ; json.load(open('{}'))" || exit 1
    - name: Install zola
      run: |
        set -x
        wget -O - \
           "https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz" \
        | sudo tar xzf - -C /usr/local/bin
    - name: Generate HTML
      run: zola build
    # Add CNAME, either (first one used)
    # - file in the root
    # - the environment variable set above
    - name: add CNAME
      run: |
        if [ -f CNAME ] ; then
            mv CNAME public/
            echo "Copied CNAME from repository root"
            exit 0
        fi
        if [ -n ${{ env.CNAME }} ] ; then
            echo -n ${{ env.CNAME }} > public/CNAME
            echo "Used CNAME from the action workflow file"
        fi
    - name: Deploy to target branch
      if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', env.SOURCE_BRANCH) && ( env.DEPLOY_ORGANIZATION == '' || github.repository_owner == env.DEPLOY_ORGANIZATION ) }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: ${{ env.PUBLISH_BRANCH }}
        force_orphan: true
